# Generated by Django 4.2.3 on 2023-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
